version: "3"
services:
  identity-api:
    container_name: backend-api
    build:
      context: ./
    volumes:
      - .:/home/node/app
    ports:
      - "${LOCALHOST_PORT}:3000"

  db:
    restart: unless-stopped
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PWD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PWD}
      - TZ=${TZ}
    ports:
      - 3310:3306
    volumes:
      - "db:/var/lib/mysql"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

volumes:
  db:

networks:
  default:
    name: backend
    external: true
